SIS/Controllers/SectionController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SIS.Data;
using SIS.Models;
using SIS.Services;

namespace SIS.Controllers
{
    [Authorize(Roles = "Manager, Student")]
    public class SectionController : Controller
    {
        ICourseService courseService;
        IInstructorService instructorService;
        ISectionService sectionService;
        public SectionController(ICourseService courseService, IInstructorService instructorService, ISectionService sectionService)
        {
            this.courseService = courseService;
            this.instructorService = instructorService;
            this.sectionService = sectionService;
        }

        public IActionResult Index(string courseName, int page)
        {
            PagedSectionResult sections = sectionService.GetAllSections(courseName, page);

            if (!sections.Sections.Any())
            {
                ViewBag.Message = "No section found.";
            }

            return View("Index", sections);
        }

        [Authorize(Roles = "Manager")]
        public IActionResult Create()
        {
            VmSection vmSection = new VmSection();

            vmSection.Course = courseService.GetAllCourses("", 0);
            vmSection.Instructor = instructorService.GetAllInstructors(0, 0);

            ViewData["isEdit"] = false;

            return View("Create", vmSection);
        }

        [Authorize(Roles = "Manager")]
        public IActionResult Save(VmSection vmSection)
        {
            sectionService.CreateSection(vmSection);

            TempData["message"] = "Section has been saved successfully.";

            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Manager")]
        public IActionResult Edit(int id)
        {
            VmSection vmSection = new VmSection();

            vmSection.Section = sectionService.GetSectionById(id);
            vmSection.Course = courseService.GetAllCourses("", 0);
            vmSection.Instructor = instructorService.GetAllInstructors(0, 0);

            ViewData["isEdit"] = true;

            return View("Create", vmSection);
        }

        [Authorize(Roles = "Manager")]
        public IActionResult Update(VmSection vmSection)
        {
            sectionService.UpdateSection(vmSection);

            TempData["message"] = "Section has been updated successfully.";

            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Manager")]
        public IActionResult Delete(int id)
        {
            sectionService.DeleteSection(id);

            TempData["message"] = "Section has been deleted successfully.";

            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Student")]
        public IActionResult GetSectionsByCourseId(int id)
        {
            List<SectionModel> sections = sectionService.GetSectionsByCourseId(id);

            return View("GetSectionsByCourseId", sections);
        }
    }
}

SIS/Views/Section/Create.cshtml
@model VmSection

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_MasterLayout.cshtml";
}

<div class="content container-fluid">

    <!-- Page Header -->
    <div class="page-header">
        <div class="row align-items-center">
            <div class="col">
                <h3 class="page-title">@( (bool)ViewData["isEdit"] ? "Edit Section" : "Add Section" )</h3>
                <ul class="breadcrumb">
                    <li class="breadcrumb-item"><a asp-controller="Section" asp-action="Index">Section</a></li>
                    <li class="breadcrumb-item active">Add Section</li>
                </ul>
            </div>
        </div>
    </div>
    <!-- /Page Header -->

    <div class="row">
        <div class="col-sm-12">

            <div class="card">
                <div class="card-body">
                    <form method="post">
                        <div class="row">
                            <div class="col-12">
                                <h5 class="form-title"><span>Section Information</span></h5>
                            </div>
                            <div class="col-12">
                                <div class="form-group local-forms">
                                    <input type="hidden" asp-for="Section.Id" class="form-control">
                                </div>
                            </div>
                            <div class="col-12 col-sm-6">
                                <div class="form-group local-forms">
                                    <label>Section Number <span class="login-danger">*</span></label>
                                    <input type="text" asp-for="Section.SectionNumber" class="form-control" placeholder="Section Number">
                                    <div class="mt-2">
                                        <span asp-validation-for="Section.SectionNumber" class="text-danger"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="col-12 col-sm-6">
                                <div class="form-group local-forms">
                                    <label>Max Capacity <span class="login-danger">*</span></label>
                                    <input type="text" asp-for="Section.MaxCapacity" class="form-control" placeholder="Max Capacity">
                                    <div class="mt-2">
                                        <span asp-validation-for="Section.MaxCapacity" class="text-danger"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="col-12 col-sm-6">
                                <div class="form-group local-forms">
                                    <label>Course <span class="login-danger">*</span></label>
                                    <select asp-for="Section.CourseId" class="form-control select select2-hidden-accessible" tabindex="-1" aria-hidden="true">
                                        <option>Please Select Course </option>
                                        @foreach (CourseModel course in Model.Course.Courses)
                                        {
                                            <option value="@course.Id">@course.Name</option>
                                        }
                                    </select>
                                    <div class="mt-2">
                                        <span asp-validation-for="Section.CourseId" class="text-danger"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="col-12 col-sm-6">
                                <div class="form-group local-forms">
                                    <label>Instructor <span class="login-danger">*</span></label>
                                    <select asp-for="Section.InstructorId" class="form-control select select2-hidden-accessible" tabindex="-1" aria-hidden="true">
                                        <option>Please Select Instructor</option>
                                        @foreach (InstructorModel instructor in Model.Instructor.Instructors)
                                        {
                                            <option value="@instructor.Id">@(instructor.FirstName + " " + instructor.LastName)</option>
                                        }
                                    </select>
                                    <div class="mt-2">
                                        <span asp-validation-for="Section.InstructorId" class="text-danger"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="student-submit text-end">
                                    @if ((bool)ViewData["isEdit"])
                                    {
                                        <button type="submit" asp-controller="Section" asp-action="Update" class="btn btn-primary">Update</button>
                                    }
                                    else
                                    {
                                        <button type="submit" asp-controller="Section" asp-action="Save" class="btn btn-primary">Save</button>
                                    }
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

        </div>
    </div>
</div>

SIS/Views/Section/GetSectionsByCourseId.cshtml
@model List<SectionModel>
@using SIS.Services
@inject IAccountService AccountService

@{
    var user = await AccountService.GetCurrentUserProfileAsync();
}

@{
    ViewData["Title"] = "GetSectionsByCourseId";
    Layout = "~/Views/Shared/_MasterLayout.cshtml";
}

<div class="content container-fluid">

    <!-- Page Header -->
    <div class="page-header">
        <div class="row">
            <div class="col-sm-12">
                <div class="page-sub-header">
                    <h3 class="page-title">Sections</h3>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a asp-controller="Dashboard" asp-action="Index">Dashboard</a></li>
                        <li class="breadcrumb-item active">Sections</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12">

            <div class="card card-table comman-shadow">
                <div class="card-body">

                    <!-- Page Header -->
                    <div class="page-header">
                        <div class="row align-items-center">
                            <div class="col">
                                <h3 class="page-title">Sections</h3>
                            </div>
                        </div>
                    </div>
                    <!-- /Page Header -->

                    <div class="table-responsive">
                        <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper dt-bootstrap4 no-footer">
                            <div class="col-sm-12">
                                <table class="table border-0 star-student table-hover table-center mb-0 datatable table-striped dataTable no-footer" id="DataTables_Table_0" role="grid" aria-describedby="DataTables_Table_0_info">
                                    <thead class="student-thread">

                                        <tr role="row">
                                            <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="Name: activate to sort column ascending" style="width: 214.988px;">Section Number</th>
                                            <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="Name: activate to sort column ascending" style="width: 214.988px;">Capacity</th>
                                            <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="Name: activate to sort column ascending" style="width: 214.988px;">Instructor Name</th>
                                            <th class="text-end sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="Action: activate to sort column ascending" style="width: 115.162px;">Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (SectionModel sec in Model)
                                        {
                                            <tr role="row" class="odd">

                                                <td>
                                                    @sec.SectionNumber
                                                </td>
                                                <td>
                                                    @sec.MaxCapacity
                                                </td>
                                                <td>
                                                    @sec.InstructorName
                                                </td>
                                                <td class="text-end">
                                                    <a asp-controller="Student" asp-action="CourseRegister" asp-route-studentId="@user.Id" asp-route-sectionId="@sec.Id" onclick="return confirm('Are you sure you want to register this course?')" class="btn btn-sm bg-success-light me-2">
                                                        Register
                                                    </a>
                                                </td>
                                            </tr>
                                        }
                                        <tr>
                                            @if (ViewBag.Message != null)
                                            {
                                                <td colspan="3" class="text-center">
                                                    @ViewBag.Message
                                                </td>
                                            }
                                        </tr>
                                    </tbody>
                                </table>

                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

SIS/Views/Section/Index.cshtml
@model PagedSectionResult

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_MasterLayout.cshtml";
}

<div class="content container-fluid">
    <!-- Page Header -->
    <div class="page-header">
        <div class="row align-items-center">
            <div class="col">
                <h3 class="page-title">Sections</h3>
                <ul class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a asp-controller="Section" asp-action="Index">
                            Section
                        </a>
                    </li>
                    <li class="breadcrumb-item active">Section</li>
                </ul>
            </div>
        </div>
    </div>
    <!-- /Page Header -->

    <div class="row">
        <form method="get" asp-controller="Section" asp-action="Index">
            <div class="row">
                <div class="col-lg-3 col-md-6">
                    <div class="form-group">
                        <input type="text" name="courseName" class="form-control" placeholder="Search by Course Name ..." value="@Context.Request.Query["searchTerm"]">
                    </div>
                </div>
                <div class="col-lg-2">
                    <div class="search-student-btn">
                        <button type="submit" class="btn btn-primary">Search</button>
                    </div>
                </div>
            </div>
        </form>
    </div>


    <div class="row">
        <div class="col-sm-12">

            <div class="card card-table comman-shadow">
                <div class="card-body">

                    <!-- Page Header -->
                    <div class="page-header">
                        <div class="row align-items-center">
                            <div class="col">
                                <h3 class="page-title">Sections</h3>
                            </div>
                            @if (User.IsInRole("Manager"))
                            {
                                <div class="col-auto text-end float-end ms-auto download-grp">
                                    <a asp-controller="Section" asp-action="Create" class="btn btn-primary">
                                        <i class="fas fa-plus"></i> New Section
                                    </a>
                                </div>
                            }
                        </div>
                    </div>
                    <!-- /Page Header -->

                    <div class="table-responsive">
                        <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper dt-bootstrap4 no-footer">
                            <div class="col-sm-12">
                                <table class="table border-0 star-student table-hover table-center mb-0 datatable table-striped dataTable no-footer" id="DataTables_Table_0" role="grid" aria-describedby="DataTables_Table_0_info">
                                    <thead class="student-thread">
                                        <tr role="row">
                                            <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="Name: activate to sort column ascending" style="width: 214.988px;">Section Number</th>
                                            <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="No of Students: activate to sort column ascending" style="width: 157.812px;">Capacity</th>
                                            <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="No of Students: activate to sort column ascending" style="width: 157.812px;">Course Name</th>
                                            <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="No of Students: activate to sort column ascending" style="width: 157.812px;">Instructor Name</th>
                                            @if (User.IsInRole("Manager"))
                                            {
                                                <th class="text-end sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="Action: activate to sort column ascending" style="width: 115.162px;">Action</th>
                                            }
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (SectionModel s in Model.Sections)
                                        {
                                            <tr role="row" class="odd">
                                                <td>
                                                    <h2>
                                                        <a>@s.SectionNumber</a>
                                                    </h2>
                                                </td>
                                                <td>@s.MaxCapacity</td>
                                                <td>@s.CourseName</td>
                                                <td>@s.InstructorName</td>
                                                @if (User.IsInRole("Manager"))
                                                {
                                                    <td class="text-end">
                                                        <div class="actions">
                                                            @* <a asp-controller="Section" asp-action="Delete" asp-route-id="@s.Id" onclick="return confirm('Are you sure you want to delete?')" class="btn btn-sm bg-success-light me-2">
                                                                <i class="feather-delete" title="Delete"></i>
                                                            </a> *@
                                                            <a class="btn btn-sm bg-success-light me-2 delete-section" data-id="@s.Id">
                                                                <i class="feather-delete" title="Delete"></i>
                                                            </a>
                                                            <a asp-controller="Section" asp-action="Edit" asp-route-id="@s.Id" class="btn btn-sm bg-danger-light">
                                                                <i class="feather-edit" title="Edit"></i>
                                                            </a>
                                                        </div>
                                                    </td>
                                                }
                                            </tr>
                                        }
                                        <tr>
                                            @if (ViewBag.Message != null)
                                            {
                                                <td colspan="5" class="text-center">
                                                    @ViewBag.Message
                                                </td>
                                            }
                                        </tr>
                                    </tbody>
                                </table>
                                <div class="mt-5">
                                    <nav class="d-flex justify-content-end" aria-label="Page navigation example">
                                        <ul class="pagination">
                                            <li class="page-item @(Model.CurrentPage == 1 ? "disabled" : "")">
                                                <a class="page-link" href="@Url.Action("Index", new { page = Model.CurrentPage - 1 })" aria-label="Previous">
                                                    <span aria-hidden="true">&laquo;</span>
                                                </a>
                                            </li>
                                            @for (int i = 1; i <= Model.TotalPages; i++)
                                            {
                                                <li class="page-item @(i == Model.CurrentPage ? "active" : "")">
                                                    <a class="page-link" href="@Url.Action("Index", new { page = i })">@i</a>
                                                </li>
                                            }
                                            <li class="page-item @(Model.CurrentPage == Model.TotalPages ? "disabled" : "")">
                                                <a class="page-link" href="@Url.Action("Index", new { page = Model.CurrentPage + 1 })" aria-label="Next">
                                                    <span aria-hidden="true">&raquo;</span>
                                                </a>
                                            </li>
                                        </ul>
                                    </nav>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>


@* =================================== Sweet Alert =============================== *@

<script>
    $(document).ready(function () {
        $(".delete-section").click(function () {
            let sectionId = $(this).data("id");

            Swal.fire({
                title: 'Are you sure?',
                text: "Are you sure you want to delete?",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
            }).then((result) => {
                if (result.isConfirmed) {
                    // Redirect to Delete action
                    window.location.href = '/Section/Delete/' + sectionId;
                }
            });
        });
    });
</script>